### ISSUE TITLE
Transitions on reveal?

### ISSUE THREAD

**Issue by vilbht** [tiagosimoes/AutoAnimations#1]
Hi there,

Been looking for a plugin like this. does the plugin fade in an element based on when it enters the viewport? For instance, in a article where text / images should subtly fade in when the user scrolls and the content becomes visible.

**Comment by tiagosimoes** [comment]
Hi vilav,

No it doesn't. This animates elements that are added / removed from DOM.

Cheers,
Tiago Simões
